# Generated by Django 5.1.4 on 2026-02-22 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10, verbose_name="متد")),
                ("path", models.CharField(max_length=500, verbose_name="مسیر")),
                (
                    "query_string",
                    models.TextField(
                        blank=True, null=True, verbose_name="پارامترهای Query"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آدرس IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "referer",
                    models.URLField(blank=True, null=True, verbose_name="Referer"),
                ),
                (
                    "status_code",
                    models.IntegerField(blank=True, null=True, verbose_name="کد وضعیت"),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="زمان پاسخ (میلی\u200cثانیه)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ درخواست",
                "verbose_name_plural": "لاگ\u200cهای درخواست",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="requestlog__timesta_6e4161_idx"
                    ),
                    models.Index(fields=["path"], name="requestlog__path_5f8022_idx"),
                    models.Index(
                        fields=["method"], name="requestlog__method_996b71_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="requestlog__status__4e280c_idx"
                    ),
                ],
            },
        ),
    ]
